[package]
name = "rust-chat-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12", features = ["attributes"] }
tokio = { version = "1.40.0", features = ["full"] }
futures = "0.3.30"
tokio-tungstenite = "0.24.0"
tungstenite = "0.24.0"

